scene: ??? # mandatory value to be passed as a command line arg
model_name: ""
data_path: data

defaults:
  - paths
  - ensembles:
      - splg
      - sift
      - disk
  - retrieval:
      - disk
  - refinement:
      - pixsfm_low_memory
  - override hydra/job_logging: custom

steps:
  - preprocess
  - get_pairs
  - extract_features
  - match_features
  - sfm
  - mvs
  - postprocess
  - compute_metrics

preprocessing:
  remove_problematic_images: true
  rotate_images: true

retrieval:
  n_matches: 300

overwrite: false

logging:
  log_dir: logs
  log_level: INFO
  verbose: false
