scene: ??? # mandatory value to be passed as a command line arg
model_name: ""
data_path: data

defaults:
  - paths
  - ensembles:
      - disk
      - sift
  - retrieval:
      - netvlad
  - refinement:
      - pixsfm_low_memory
  - override hydra/job_logging: custom
  - _self_

steps:
  - preprocess
  - get_pairs
  - extract_features
  - match_features
  - sfm
  - mvs
  - postprocess
  - compute_metrics

preprocessing:
  remove_problematic_images: true
  rotate_images: false

retrieval:
  n_matches: 50

postprocessing:
  max_size: 1600 # during image processing steps
  segmentation_model: segformer # segformer, beit or hrnet

overwrite: false

logging:
  log_dir: logs
  log_level: INFO
  verbose: false
