paths:
  data: ${..data_path}/${..scene}
  images: ${.data}/images

  features_retrieval: ${.data}/features/${..retrieval.name}.h5
  pairs: ${.data}/matches/retrieval/${..retrieval.name}-${..retrieval.n_matches}.txt

  features: ${.data}/features/${..model_name}.h5
  matches: ${.data}/matches/${..model_name}.h5

  sparse: ${.data}/sparse/${..model_name}
  refined_sparse: ${.data}/sparse/${..model_name}/refined
  db: ${.sparse}/database.db
  dense: ${.data}/dense/${..model_name}

  metrics: ${.data}/metrics/${..model_name}
  results: ${.data}/results/${..model_name}
  visualizations: ${.data}/visualizations/${..model_name}

  cache: cache
