defaults:
  - paths

scene: ??? # mandatory value to be passed as a command line arg
model_name: ""
data_path: data

steps:
- preprocess
- get_pairs
- extract_features
- match_features
- sfm
- refinement
- mvs
- postprocess
- compute_metrics

preprocessing:
  rotate_images: true

retrieval:
  name: netvlad
  n_matches: 50

# TODO: add support for ensembles
features: superpoint_max
matcher: superglue

refinement:
  steps: "" # "", KA, BA or KA+BA
  low_memory: false

colmap: false
overwrite: true
evaluate: false # set to true if there is a sparse baseline model

logging:
  log_dir: logs
  log_level: INFO
  verbose: false
