scene: ??? # mandatory value to be passed as a command line arg
data_path: data

steps:
- preprocess
- get_pairs
- extract_features
- match_features
- sfm
- refinement
- mvs
- postprocess
- collect_metrics # TODO: this should be a pipeline step imo

retrieval:
  name: netvlad
  n_matches: 50

# TODO: add support for ensembles
features: superpoint_max
matcher: superglue

refinement:
  steps: KA+BA
  low_memory: false

colmap: false
overwrite: true
evaluate: false # TODO: remove this once collect_metrics is a pipeline step

logging:
  log_dir: logs
  log_level: INFO
  verbose: false
