scene: ??? # mandatory value to be passed as a command line arg
model_name: ""
data_path: data

steps:
- preprocess
- get_pairs
- extract_features
- match_features
- sfm
- refinement
- mvs
- postprocess
- compute_metrics

retrieval:
  name: netvlad
  n_matches: 50

# TODO: add support for ensembles
features: superpoint_max
matcher: superglue

refinement:
  steps: "" # "", KA, BA or KA+BA
  low_memory: false

colmap: false
overwrite: true
evaluate: false # set to true if there is a sparse baseline model

paths:
  data: ${..data_path}/${..scene}
  images: ${.data}/images

  features_retrieval: ${.data}/features/${..retrieval.name}.h5
  matches_retrieval: ${.data}/matches/retrieval/${..retrieval.name}-${..retrieval.n_matches}.txt

  features: ${.data}/features/${..features}.h5
  matches: ${.data}/matches/${..model_name}.h5

  sparse: ${.data}/sparse/${..model_name}
  sparse_baseline: ${.data}/sparse/baseline
  refined_sparse: ${.data}/sparse/${..model_name}/refined
  db: ${.sparse}/database.db
  dense: ${.data}/dense/${..model_name}
  baseline_model: ${.data}/sparse/baseline

  metrics: ${.data}/metrics/${..model_name}
  results: ${.data}/results/${..model_name}
  visualizations: ${.data}/visualizations/${..model_name}

  cache: cache

logging:
  log_dir: logs
  log_level: INFO
  verbose: false
